// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: creator.proto

package proto

import (
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	protos "models/protos"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatorLinkType int32

const (
	CreatorLinkType_OTHER            CreatorLinkType = 0
	CreatorLinkType_WEBSITE          CreatorLinkType = 1
	CreatorLinkType_PATREON          CreatorLinkType = 2
	CreatorLinkType_YOUTUBE          CreatorLinkType = 3
	CreatorLinkType_FACEBOOK         CreatorLinkType = 4
	CreatorLinkType_INSTAGRAM        CreatorLinkType = 5
	CreatorLinkType_TWITTER          CreatorLinkType = 6
	CreatorLinkType_DISCORD          CreatorLinkType = 7
	CreatorLinkType_KICKSTARTER      CreatorLinkType = 8
	CreatorLinkType_TIKTOK           CreatorLinkType = 9
	CreatorLinkType_THINGIVERSE      CreatorLinkType = 10
	CreatorLinkType_CGTRADER         CreatorLinkType = 11
	CreatorLinkType_CULTS3D          CreatorLinkType = 12
	CreatorLinkType_MYMINIFACTORY    CreatorLinkType = 13
	CreatorLinkType_PRINTABLES       CreatorLinkType = 14
	CreatorLinkType_PRINTED_WARGAMES CreatorLinkType = 15
	CreatorLinkType_ETSY             CreatorLinkType = 16
)

// Enum value maps for CreatorLinkType.
var (
	CreatorLinkType_name = map[int32]string{
		0:  "OTHER",
		1:  "WEBSITE",
		2:  "PATREON",
		3:  "YOUTUBE",
		4:  "FACEBOOK",
		5:  "INSTAGRAM",
		6:  "TWITTER",
		7:  "DISCORD",
		8:  "KICKSTARTER",
		9:  "TIKTOK",
		10: "THINGIVERSE",
		11: "CGTRADER",
		12: "CULTS3D",
		13: "MYMINIFACTORY",
		14: "PRINTABLES",
		15: "PRINTED_WARGAMES",
		16: "ETSY",
	}
	CreatorLinkType_value = map[string]int32{
		"OTHER":            0,
		"WEBSITE":          1,
		"PATREON":          2,
		"YOUTUBE":          3,
		"FACEBOOK":         4,
		"INSTAGRAM":        5,
		"TWITTER":          6,
		"DISCORD":          7,
		"KICKSTARTER":      8,
		"TIKTOK":           9,
		"THINGIVERSE":      10,
		"CGTRADER":         11,
		"CULTS3D":          12,
		"MYMINIFACTORY":    13,
		"PRINTABLES":       14,
		"PRINTED_WARGAMES": 15,
		"ETSY":             16,
	}
)

func (x CreatorLinkType) Enum() *CreatorLinkType {
	p := new(CreatorLinkType)
	*p = x
	return p
}

func (x CreatorLinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreatorLinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_creator_proto_enumTypes[0].Descriptor()
}

func (CreatorLinkType) Type() protoreflect.EnumType {
	return &file_creator_proto_enumTypes[0]
}

func (x CreatorLinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreatorLinkType.Descriptor instead.
func (CreatorLinkType) EnumDescriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{0}
}

type Creator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description *string        `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Links       []*CreatorLink `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Tags        []*protos.Tag  `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Creator) Reset() {
	*x = Creator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_creator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Creator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Creator) ProtoMessage() {}

func (x *Creator) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Creator.ProtoReflect.Descriptor instead.
func (*Creator) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{0}
}

func (x *Creator) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Creator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Creator) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Creator) GetLinks() []*CreatorLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Creator) GetTags() []*protos.Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreatorLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Link string          `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Type CreatorLinkType `protobuf:"varint,3,opt,name=type,proto3,enum=creator.CreatorLinkType" json:"type,omitempty"`
}

func (x *CreatorLink) Reset() {
	*x = CreatorLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_creator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatorLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatorLink) ProtoMessage() {}

func (x *CreatorLink) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatorLink.ProtoReflect.Descriptor instead.
func (*CreatorLink) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{1}
}

func (x *CreatorLink) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatorLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreatorLink) GetType() CreatorLinkType {
	if x != nil {
		return x.Type
	}
	return CreatorLinkType_OTHER
}

var File_creator_proto protoreflect.FileDescriptor

var file_creator_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x12, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2f, 0x67, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x74, 0x61,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x01, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2a,
	0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x54,
	0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x3a, 0x06, 0xba, 0xb9, 0x19, 0x02, 0x08, 0x01,
	0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x67, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x3a, 0x06, 0xba, 0xb9, 0x19, 0x02, 0x08, 0x01, 0x2a, 0x86, 0x02, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x45, 0x42, 0x53,
	0x49, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x41, 0x54, 0x52, 0x45, 0x4f, 0x4e,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x59, 0x4f, 0x55, 0x54, 0x55, 0x42, 0x45, 0x10, 0x03, 0x12,
	0x0c, 0x0a, 0x08, 0x46, 0x41, 0x43, 0x45, 0x42, 0x4f, 0x4f, 0x4b, 0x10, 0x04, 0x12, 0x0d, 0x0a,
	0x09, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07,
	0x54, 0x57, 0x49, 0x54, 0x54, 0x45, 0x52, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x49, 0x53,
	0x43, 0x4f, 0x52, 0x44, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x4b, 0x49, 0x43, 0x4b, 0x53, 0x54,
	0x41, 0x52, 0x54, 0x45, 0x52, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x49, 0x4b, 0x54, 0x4f,
	0x4b, 0x10, 0x09, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x48, 0x49, 0x4e, 0x47, 0x49, 0x56, 0x45, 0x52,
	0x53, 0x45, 0x10, 0x0a, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x47, 0x54, 0x52, 0x41, 0x44, 0x45, 0x52,
	0x10, 0x0b, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x55, 0x4c, 0x54, 0x53, 0x33, 0x44, 0x10, 0x0c, 0x12,
	0x11, 0x0a, 0x0d, 0x4d, 0x59, 0x4d, 0x49, 0x4e, 0x49, 0x46, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x59,
	0x10, 0x0d, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x49, 0x4e, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x53,
	0x10, 0x0e, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x52, 0x49, 0x4e, 0x54, 0x45, 0x44, 0x5f, 0x57, 0x41,
	0x52, 0x47, 0x41, 0x4d, 0x45, 0x53, 0x10, 0x0f, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x54, 0x53, 0x59,
	0x10, 0x10, 0x42, 0x0e, 0x5a, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_creator_proto_rawDescOnce sync.Once
	file_creator_proto_rawDescData = file_creator_proto_rawDesc
)

func file_creator_proto_rawDescGZIP() []byte {
	file_creator_proto_rawDescOnce.Do(func() {
		file_creator_proto_rawDescData = protoimpl.X.CompressGZIP(file_creator_proto_rawDescData)
	})
	return file_creator_proto_rawDescData
}

var file_creator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_creator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_creator_proto_goTypes = []interface{}{
	(CreatorLinkType)(0), // 0: creator.CreatorLinkType
	(*Creator)(nil),      // 1: creator.Creator
	(*CreatorLink)(nil),  // 2: creator.CreatorLink
	(*protos.Tag)(nil),   // 3: tag.Tag
}
var file_creator_proto_depIdxs = []int32{
	2, // 0: creator.Creator.links:type_name -> creator.CreatorLink
	3, // 1: creator.Creator.tags:type_name -> tag.Tag
	0, // 2: creator.CreatorLink.type:type_name -> creator.CreatorLinkType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_creator_proto_init() }
func file_creator_proto_init() {
	if File_creator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_creator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Creator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_creator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatorLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_creator_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_creator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_creator_proto_goTypes,
		DependencyIndexes: file_creator_proto_depIdxs,
		EnumInfos:         file_creator_proto_enumTypes,
		MessageInfos:      file_creator_proto_msgTypes,
	}.Build()
	File_creator_proto = out.File
	file_creator_proto_rawDesc = nil
	file_creator_proto_goTypes = nil
	file_creator_proto_depIdxs = nil
}
