// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: form.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FormValidationType int32

const (
	FormValidationType_ERROR   FormValidationType = 0
	FormValidationType_WARNING FormValidationType = 1
	FormValidationType_INFO    FormValidationType = 2
)

// Enum value maps for FormValidationType.
var (
	FormValidationType_name = map[int32]string{
		0: "ERROR",
		1: "WARNING",
		2: "INFO",
	}
	FormValidationType_value = map[string]int32{
		"ERROR":   0,
		"WARNING": 1,
		"INFO":    2,
	}
)

func (x FormValidationType) Enum() *FormValidationType {
	p := new(FormValidationType)
	*p = x
	return p
}

func (x FormValidationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormValidationType) Descriptor() protoreflect.EnumDescriptor {
	return file_form_proto_enumTypes[0].Descriptor()
}

func (FormValidationType) Type() protoreflect.EnumType {
	return &file_form_proto_enumTypes[0]
}

func (x FormValidationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormValidationType.Descriptor instead.
func (FormValidationType) EnumDescriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{0}
}

type FormOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Required    bool              `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	Disabled    bool              `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ReadOnly    bool              `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Visible     bool              `protobuf:"varint,4,opt,name=visible,proto3" json:"visible,omitempty"`
	Validations []*FormValidation `protobuf:"bytes,5,rep,name=validations,proto3" json:"validations,omitempty"`
}

func (x *FormOptions) Reset() {
	*x = FormOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormOptions) ProtoMessage() {}

func (x *FormOptions) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormOptions.ProtoReflect.Descriptor instead.
func (*FormOptions) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{0}
}

func (x *FormOptions) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FormOptions) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *FormOptions) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *FormOptions) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *FormOptions) GetValidations() []*FormValidation {
	if x != nil {
		return x.Validations
	}
	return nil
}

type FormLengthOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Max int32 `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Min int32 `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
}

func (x *FormLengthOptions) Reset() {
	*x = FormLengthOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormLengthOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormLengthOptions) ProtoMessage() {}

func (x *FormLengthOptions) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormLengthOptions.ProtoReflect.Descriptor instead.
func (*FormLengthOptions) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{1}
}

func (x *FormLengthOptions) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *FormLengthOptions) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

type FormValidation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type    FormValidationType `protobuf:"varint,2,opt,name=type,proto3,enum=form.FormValidationType" json:"type,omitempty"`
}

func (x *FormValidation) Reset() {
	*x = FormValidation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormValidation) ProtoMessage() {}

func (x *FormValidation) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormValidation.ProtoReflect.Descriptor instead.
func (*FormValidation) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{2}
}

func (x *FormValidation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FormValidation) GetType() FormValidationType {
	if x != nil {
		return x.Type
	}
	return FormValidationType_ERROR
}

type FormSelectOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options []*FormSelectOption `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *FormSelectOptions) Reset() {
	*x = FormSelectOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormSelectOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormSelectOptions) ProtoMessage() {}

func (x *FormSelectOptions) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormSelectOptions.ProtoReflect.Descriptor instead.
func (*FormSelectOptions) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{3}
}

func (x *FormSelectOptions) GetOptions() []*FormSelectOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type FormSelectOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label    string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Disabled bool   `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
}

func (x *FormSelectOption) Reset() {
	*x = FormSelectOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormSelectOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormSelectOption) ProtoMessage() {}

func (x *FormSelectOption) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormSelectOption.ProtoReflect.Descriptor instead.
func (*FormSelectOption) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{4}
}

func (x *FormSelectOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FormSelectOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FormSelectOption) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

var File_form_proto protoreflect.FileDescriptor

var file_form_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x6f,
	0x72, 0x6d, 0x22, 0xb4, 0x01, 0x0a, 0x0b, 0x46, 0x6f, 0x72, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65,
	0x61, 0x64, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72,
	0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x12, 0x36, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x46, 0x6f,
	0x72, 0x6d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x37, 0x0a, 0x11, 0x46, 0x6f, 0x72,
	0x6d, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d,
	0x69, 0x6e, 0x22, 0x58, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x6d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x45, 0x0a, 0x11,
	0x46, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x30, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x5a, 0x0a, 0x10, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x2a,
	0x36, 0x0a, 0x12, 0x46, 0x6f, 0x72, 0x6d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x02, 0x42, 0x0e, 0x5a, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_form_proto_rawDescOnce sync.Once
	file_form_proto_rawDescData = file_form_proto_rawDesc
)

func file_form_proto_rawDescGZIP() []byte {
	file_form_proto_rawDescOnce.Do(func() {
		file_form_proto_rawDescData = protoimpl.X.CompressGZIP(file_form_proto_rawDescData)
	})
	return file_form_proto_rawDescData
}

var file_form_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_form_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_form_proto_goTypes = []interface{}{
	(FormValidationType)(0),   // 0: form.FormValidationType
	(*FormOptions)(nil),       // 1: form.FormOptions
	(*FormLengthOptions)(nil), // 2: form.FormLengthOptions
	(*FormValidation)(nil),    // 3: form.FormValidation
	(*FormSelectOptions)(nil), // 4: form.FormSelectOptions
	(*FormSelectOption)(nil),  // 5: form.FormSelectOption
}
var file_form_proto_depIdxs = []int32{
	3, // 0: form.FormOptions.validations:type_name -> form.FormValidation
	0, // 1: form.FormValidation.type:type_name -> form.FormValidationType
	5, // 2: form.FormSelectOptions.options:type_name -> form.FormSelectOption
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_form_proto_init() }
func file_form_proto_init() {
	if File_form_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_form_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormLengthOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormValidation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormSelectOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormSelectOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_form_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_form_proto_goTypes,
		DependencyIndexes: file_form_proto_depIdxs,
		EnumInfos:         file_form_proto_enumTypes,
		MessageInfos:      file_form_proto_msgTypes,
	}.Build()
	File_form_proto = out.File
	file_form_proto_rawDesc = nil
	file_form_proto_goTypes = nil
	file_form_proto_depIdxs = nil
}
